### PR TITLE
Updated to use node-usb-native, updated to latest vscode version

### PR DESCRIPTION
**Pull request by jarl-dk**
This fixes issue #6 and #7

### CODE REVIEW

**Comment by curdeveryday** [comment]
Have you verified it worked? It doesn't work in my vscode. It still warn the mismatch.
image
image

**Comment by jarl-dk** [comment]
@curdeveryday  I have verified it working on the latest vscode (built from source), which vscode version are you using? Can you attach an image with the version dialog?

**Comment by jarl-dk** [comment]
you should ensure
```
git clean -fdX
yarn cache clean
yarn
```

And then open the folder from a recent vscode.

**Comment by curdeveryday** [comment]
Okay, it works now.Thanks.

**Pull request merged**
