### PR TITLE
Migration to typescript + refactoring

### PR DESCRIPTION
**Pull request by darul75**
Extension is now fully refactored in typescript, work has consisted in debugging from scratch the whole application and extracting main components to make them easier to sustain.

Remaining issues to be discussed:

- Whole process for dealing with node bindings and electron, I ended up using base SerialPort dependency and copying the binding file into a build folder, I am not sure it is the easiest way. Using usbnode module is not easy and I got errors when running the command you provided against different version of Node, I use nvm locally to be able to switch between different version
- CRC errors: the run command is not always working well...transferring the codebase to be executed as a string does not always work.
- CRC errors: uploading a binary file like a png often results in a CRC Errors 2k.

Happy to discuss this with you @curdeveryday

### CODE REVIEW

**Comment by curdeveryday** [comment]
Glad to receive your PR. I will try it ASAP.

About the problem of the serialport dependency, it is really a annoying problem. I must update it manually when VSCode update the electron. But I have a private repo to rebuild the module by the version of electron. I once thought of checking the update of VSCode to automatically rebuild the serialport module and then publish this extension automatically.

**Comment by darul75** [comment]
you can run

`yarn` to install all deps as usual

my post build step is here, adapt it to the version of your vscode, as a result it copies a binary file into a build folder, not sure it is perfect though.

"postinstall": "./build.sh"

according to me more important issues are with the CRC errors we got very often when trying to upload or run a script into the device

**Comment by curdeveryday** [comment]
Hi @darul75 

First, I am very sorry.  Because of my wrong operation, your commit history became mine when I merge conflict. You are not in the list of contributors. I am very sorry about that. Therefore I add a AUTHORS file to show the contributors.

I have tried running your code. It is stable for me to upload file.  It doesn't appear the errors of CRC. Could you provide me with the files you uploaded?

**Comment by darul75** [comment]
Hi @curdeveryday,

That is fine, at least I did not all this work for nothing and I think we will be in better state now to make improvements which is the main thing that matters for me. I got few other minus changes to make. Glad to hear it works well. I am on a Mac and since the very beginning I got connectivity issues with UIFlow in general, I have tried re installing latest ESP32 driver but so far it does work very well. I will make a small record to show you the kind of errors I can get.

**Comment by darul75** [comment]
Also got a windows machine where things use to work better, will make some more tests? Do you like this refactoring?

**Comment by curdeveryday** [comment]
Of course I like. I test it on my Apple Silicon. It works stable too. I will test it on a Ubuntu machine later.

**Comment by darul75** [comment]
Cool, next time do not mess up with my commits ;)

**Pull request merged**
